message: BG Conifg POC dev profile value!
password: '{cipher}AQA1V2LI7r9dkrVrH4b8zbnSmib6IUrcRLF4xqIbVm8Xq3iteQ8461pnZmcJswTJOsFPCgyn3ZwQ4S9KSIfQXGvHxpgJa0MUlby4wSAs2O9t4ILsGkFtD0N9mR2EJkmdVmEsaRrP/l5FdrJq/LfGVm4jvhJJzUgt6wa2z91KWaz77AhNekVr6e4mvEkADqrErY80B5fjudi4n4bBwwQUNKt8pdmuU2pgiUFDfCKAl8a0MeSdE+MWZDIeJmCEovhDxTdS7BHpMYu3ctANMNlE0sV9d2QSNhlYDN8Kwg7F/W4GbHLlEyN3deRpTQbcbHdNXm3EkRNANKlgfbo8ZHNkJudvjgRRJgiM8fimP8TIBQbnLA+fvHzLxMRtlsYfx/Dy7nA='

